site_name: Hướng dẫn sử dụng cty Trung Dũng
theme:
  name: material
  language: vi
  palette:
    scheme: slate
repo_url: https://github.com/quocvuong1105/Wiki-TrungDung
plugins:
  - git-revision-date-localized:
      enable_creation_date: false
      type: timeago
nav:
  - 'index.md'
  - 'caidat.md'
  - 'sudung.md'
